name: gallery
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  get: ^5.0.0-release-candidate-5
  infinite_scroll_pagination: ^4.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test: 
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/gallery.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/gallery.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"

flutter: 
  uses-material-design: true

